[build-system]
requires = [ "flit_core >=2,<3", "setuptools", "toml"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "poser"
author = "deathbeds"
author-email = ""
home-page = "https://github.com/deathbeds/poser"
classifiers = []
description-file = "readme.md"
requires = [ "click"]
license = "BSD 3-Clause \"New\" or \"Revised\" License"

[tool.flit.scripts]

[tool.flit.metadata.urls]
